### ISSUE TITLE
How to generate API types?

### ISSUE THREAD

**Issue by Rei-x** [JacobLinCool/moodle-api#13]
hello, thank you for this awesome library!

i'm really curious, how did you manage to generate all of the API types? Can you provide me with some info on how to generate them? I would be really grateful.

**Comment by JacobLinCool** [comment]
Hi,

It just a little work on reversing engineering Moodle's code, available [here](https://github.com/JacobLinCool/moodle-external-api). This tool involves injecting a PHP file into Moodle to export the internal structures of its API functions as JSON. These structures are then transformed into equivalents in Rust and TypeScript.

**Comment by Rei-x** [comment]
thank you so much for help!
